### ISSUE TITLE
feature request: TLS version

### ISSUE THREAD

**Issue by bsiegel** [bsiegel/http2-indicator#10]
Should be relatively simple, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/getSecurityInfo

**Comment by hpvd** [comment]
+1

**Comment by seamlik** [comment]
Isn't this info already retrievable by clicking the button on the left of the address bar? (Not sure the name of it though)

**Comment by bsiegel** [comment]
> Isn't this info already retrievable by clicking the button on the left of the address bar? (Not sure the name of it though)

Yep, but would be nice to have here right next to the other HTTP connection info.

**Comment by johnp** [comment]
[IndicateTLS](https://github.com/jannispinter/indicatetls) has this.

**Comment by bsiegel** [comment]
Closing this. I think keeping the addon simple and with a singular focus is best. Users can install the above-mentioned addon for this functionality.
