### ISSUE TITLE
manifest.json claims it has a content script, but there is none present

### ISSUE THREAD

**Issue by siebenmann** [bsiegel/http2-indicator#12]
The current manifest.json claims that this addon has a content script, `content.js`, that is injected on all web sites, in all frames, and runs at document start (according to the `content_scripts` key). However, there doesn't seem to be any such content script present, so this may be a lingering carry-over from a previous version of the extension. I suspect that it's worth removing this if it's truly not necessary, because I believe it's the reason that AMO currently reports that the extension requires the relatively scary permission to access your data for all websites.

(Alternately, maybe there is supposed to be a content.js and with it absent, some functionality is quietly broken.)

**Comment by bsiegel** [comment]
Thanks for the report. This is fixed in c278279 which will be included in version 3.1 of the addon.
