### ISSUE TITLE
icon not showing in current 57b5 (notwithstanding 58)

### ISSUE THREAD

**Issue by n8v8R** [bsiegel/http2-indicator#3]
Maybe is conflicting with the container icon and/or unified address/search bar

**Comment by bsiegel** [comment]
Can you provide a list of your installed addons? It appears to be working for me under 57b5 (tested on Windows and Mac).

**Comment by n8v8R** [comment]
It works properly now after having updated the extention Multi-Account Containers to v 4.0.3
